### ISSUE TITLE
-O2에서만 작동이 안 되는 코드가 있습니다.

### ISSUE THREAD

**Issue by Sait2000** [aheui/rpaheui#16]
```
$ python2 rpaheui/rpaheui.py ./aheui-aheui.aheui -O1 <snippets/hello-world/hello-world.puzzlet.aheui 
[Warning] It is running without rlib/jit.
Hello, world!
$ python2 rpaheui/rpaheui.py ./aheui-aheui.aheui -O0 <snippets/hello-world/hello-world.puzzlet.aheui                              
[Warning] It is running without rlib/jit.
Hello, world!
$ python2 rpaheui/rpaheui.py ./aheui-aheui.aheui -O2 <snippets/hello-world/hello-world.puzzlet.aheui                              
[Warning] It is running without rlib/jit.
Traceback (most recent call last):
  File "rpaheui/rpaheui.py", line 19, in <module>
    sys.exit(entry_point(sys.argv))
  File "/home/ubuntu/workspace/rpaheui/aheui/aheui.py", line 559, in entry_point
    compiler = prepare_compiler(contents, int(str_opt_level), source, aheuic_output, add_debug_info)
  File "/home/ubuntu/workspace/rpaheui/aheui/aheui.py", line 534, in prepare_compiler
    compiler.optimize2()
  File "/home/ubuntu/workspace/rpaheui/aheui/compile.py", line 374, in optimize2
    self.optimize_jump()
  File "/home/ubuntu/workspace/rpaheui/aheui/compile.py", line 418, in optimize_jump
    op, operand = self.lines[direct_target]
IndexError: list index out of range
```

https://gist.github.com/Sait2000/e4fd8e6b30a85809c08865da137207c7

**Comment by mhsrn21** [comment]
-O1도 [aheui/snippets](https://github.com/aheui/snippets)의 pi.jinseo.aheui를 통과 못 하고 Segmentation fault가 뜨네요.
-O0는 통과합니다.
