### ISSUE TITLE
설치가 안됩니다

### ISSUE THREAD

**Issue by Seojune** [aheui/rpaheui#9]
Ubuntu에서 apt install pypy로 pypy를 설치한 후 rpaheui에서 make install을 하면 설치가 진행되다
`
[translation:info] Error:
   File "/home/vantaa/pypy/rpython/translator/goal/translate.py", line 318, in main
    drv.proceed(goals)
   File "/home/vantaa/pypy/rpython/translator/driver.py", line 551, in proceed
    result = self._execute(goals, task_skip = self._maybe_skip())
   File "/home/vantaa/pypy/rpython/translator/tool/taskengine.py", line 114, in _execute
    res = self._do(goal, taskcallable, *args, **kwds)
   File "/home/vantaa/pypy/rpython/translator/driver.py", line 278, in _do
    res = func()
   File "/home/vantaa/pypy/rpython/translator/driver.py", line 359, in task_pyjitpl_lltype
    from rpython.jit.metainterp.warmspot import apply_jit
   File "/home/vantaa/pypy/rpython/jit/metainterp/warmspot.py", line 21, in <module>
    from rpython.jit.metainterp import history, pyjitpl, gc, memmgr, jitexc
   File "/home/vantaa/pypy/rpython/jit/metainterp/pyjitpl.py", line 8, in <module>
    from rpython.jit.metainterp import history, compile, resume, executor, jitexc
   File "/home/vantaa/pypy/rpython/jit/metainterp/executor.py", line 14, in <module>
    from rpython.jit.metainterp.blackhole import BlackholeInterpreter, NULL
   File "/home/vantaa/pypy/rpython/jit/metainterp/blackhole.py", line 16, in <module>
    from rpython.rlib.jit_libffi import CIF_DESCRIPTION_P
   File "/home/vantaa/pypy/rpython/rlib/jit_libffi.py", line 4, in <module>
    from rpython.rlib import clibffi, jit
   File "/home/vantaa/pypy/rpython/rlib/clibffi.py", line 82, in <module>
    include_dirs = platform.include_dirs_for_libffi(),
   File "/home/vantaa/pypy/rpython/translator/platform/__init__.py", line 240, in include_dirs_for_libffi
    dirs = self._include_dirs_for_libffi()
   File "/home/vantaa/pypy/rpython/translator/platform/linux.py", line 33, in _include_dirs_for_libffi
    check_result_dir=True)
   File "/home/vantaa/pypy/rpython/translator/platform/posix.py", line 91, in _pkg_config
    raise ValueError(msg)
[translation:ERROR] ValueError: running 'pkg-config libffi --cflags-only-I' failed:
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing 'libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
and the default ['/usr/include/libffi'] is not a valid directory
[translation] start debugger...
> /home/vantaa/pypy/rpython/translator/platform/posix.py(91)_pkg_config()
-> raise ValueError(msg)
(Pdb+) 
Traceback (most recent call last):
  File "../pypy/rpython/bin/rpython", line 20, in <module>
    main()
  File "/home/vantaa/pypy/rpython/translator/goal/translate.py", line 325, in main
    debug(True)
  File "/home/vantaa/pypy/rpython/translator/goal/translate.py", line 278, in debug
    pdb_plus_show.start(tb)
  File "/home/vantaa/pypy/rpython/translator/tool/pdbplus.py", line 442, in start
    fn(*args)
  File "/home/vantaa/pypy/rpython/translator/tool/pdbplus.py", line 25, in post_mortem
    self.interaction(t.tb_frame, t)
  File "/usr/lib/pypy/lib-python/2.7/pdb.py", line 210, in interaction
    self.cmdloop()
  File "/usr/lib/pypy/lib-python/2.7/cmd.py", line 130, in cmdloop
    line = raw_input(self.prompt)
  File "/usr/lib/pypy/lib_pypy/pyrepl/readline.py", line 258, in raw_input
    return reader.readline(startup_hook=self.startup_hook)
  File "/usr/lib/pypy/lib_pypy/pyrepl/reader.py", line 604, in readline
    self.handle1()
  File "/usr/lib/pypy/lib_pypy/pyrepl/reader.py", line 587, in handle1
    self.do_cmd(cmd)
  File "/usr/lib/pypy/lib_pypy/pyrepl/reader.py", line 534, in do_cmd
    cmd.do()
  File "/usr/lib/pypy/lib_pypy/pyrepl/commands.py", line 184, in do
    os.kill(os.getpid(), signal.SIGINT)
KeyboardInterrupt
Makefile:16: 'aheui-c' 타겟에 대한 명령이 실패했습니다
make: *** [aheui-c] 오류 1
`
KeyboardInterrupt
Makefile:16: 'aheui-c' 타겟에 대한 명령이 실패했습니다
make: *** [aheui-c] 오류 1`

이렇게 에러가 납니다.
제가 리눅스를 잘 몰라서 제가 잘못했을 가능성이 큰 것 같은데.. 어떻게 해야 될지를 모르겠습니다

**Comment by minacle** [comment]
`apt install libffi`

**Comment by Seojune** [comment]
apt install libffi-dev를 하고나서 다시 시도하니 몇분동안 진행되다가

[translation:info] Error:
   File "/home/vantaa/pypy/rpython/translator/goal/translate.py", line 318, in main
    drv.proceed(goals)
   File "/home/vantaa/pypy/rpython/translator/driver.py", line 551, in proceed
    result = self._execute(goals, task_skip = self._maybe_skip())
   File "/home/vantaa/pypy/rpython/translator/tool/taskengine.py", line 114, in _execute
    res = self._do(goal, taskcallable, *args, **kwds)
   File "/home/vantaa/pypy/rpython/translator/driver.py", line 278, in _do
    res = func()
   File "/home/vantaa/pypy/rpython/translator/driver.py", line 359, in task_pyjitpl_lltype
    from rpython.jit.metainterp.warmspot import apply_jit
   File "/home/vantaa/pypy/rpython/jit/metainterp/warmspot.py", line 21, in <module>
    from rpython.jit.metainterp import history, pyjitpl, gc, memmgr, jitexc
   File "/home/vantaa/pypy/rpython/jit/metainterp/pyjitpl.py", line 8, in <module>
    from rpython.jit.metainterp import history, compile, resume, executor, jitexc
   File "/home/vantaa/pypy/rpython/jit/metainterp/executor.py", line 14, in <module>
    from rpython.jit.metainterp.blackhole import BlackholeInterpreter, NULL
   File "/home/vantaa/pypy/rpython/jit/metainterp/blackhole.py", line 16, in <module>
    from rpython.rlib.jit_libffi import CIF_DESCRIPTION_P
   File "/home/vantaa/pypy/rpython/rlib/jit_libffi.py", line 4, in <module>
    from rpython.rlib import clibffi, jit
   File "/home/vantaa/pypy/rpython/rlib/clibffi.py", line 82, in <module>
    include_dirs = platform.include_dirs_for_libffi(),
   File "/home/vantaa/pypy/rpython/translator/platform/__init__.py", line 240, in include_dirs_for_libffi
    dirs = self._include_dirs_for_libffi()
   File "/home/vantaa/pypy/rpython/translator/platform/linux.py", line 33, in _include_dirs_for_libffi
    check_result_dir=True)
   File "/home/vantaa/pypy/rpython/translator/platform/posix.py", line 91, in _pkg_config
    raise ValueError(msg)
[translation:ERROR] ValueError: running 'pkg-config libffi --cflags-only-I' failed:
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
and the default ['/usr/include/libffi'] is not a valid directory
[translation] start debugger...
> /home/vantaa/pypy/rpython/translator/platform/posix.py(91)_pkg_config()
-> raise ValueError(msg)
(Pdb+) 
Traceback (most recent call last):
  File "../pypy/rpython/bin/rpython", line 20, in <module>
    main()
  File "/home/vantaa/pypy/rpython/translator/goal/translate.py", line 325, in main
    debug(True)
  File "/home/vantaa/pypy/rpython/translator/goal/translate.py", line 278, in debug
    pdb_plus_show.start(tb)
  File "/home/vantaa/pypy/rpython/translator/tool/pdbplus.py", line 442, in start
    fn(*args)
  File "/home/vantaa/pypy/rpython/translator/tool/pdbplus.py", line 25, in post_mortem
    self.interaction(t.tb_frame, t)
  File "/usr/lib/pypy/lib-python/2.7/pdb.py", line 210, in interaction
    self.cmdloop()
  File "/usr/lib/pypy/lib-python/2.7/cmd.py", line 130, in cmdloop
    line = raw_input(self.prompt)
  File "/usr/lib/pypy/lib_pypy/pyrepl/readline.py", line 258, in raw_input
    return reader.readline(startup_hook=self.startup_hook)
  File "/usr/lib/pypy/lib_pypy/pyrepl/reader.py", line 604, in readline
    self.handle1()
  File "/usr/lib/pypy/lib_pypy/pyrepl/reader.py", line 587, in handle1
    self.do_cmd(cmd)
  File "/usr/lib/pypy/lib_pypy/pyrepl/reader.py", line 534, in do_cmd
    cmd.do()
  File "/usr/lib/pypy/lib_pypy/pyrepl/commands.py", line 184, in do
    os.kill(os.getpid(), signal.SIGINT)
KeyboardInterrupt
Makefile:16: 'aheui-c' 타겟에 대한 명령이 실패했습니다
make: *** [aheui-c] 오류 1

이렇게 다시 에러가 납니다

**Comment by minacle** [comment]
`libffi-dev` 가 아니라 `libffi6` 을 설치해야 했던 거 아닐까요?

**Comment by Seojune** [comment]
아까 로그를 잘못 올렸네요
[translation:info] written: /tmp/usession-default-9/testing_1/testing_1.c
[8523] translation-task}
[translation:info] Compiling c source...
[8523] {translation-task
starting compile_c
[platform:execute] make  in /tmp/usession-default-9/testing_1
[platform:WARNING] rjitlog.c: In function ‘jitlog_write_marked’:
[platform:WARNING] rjitlog.c:97:5: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
[platform:WARNING]      write(jitlog_fd, text, length);
[platform:WARNING]      ^
[translation:info] created: /home/vantaa/rpaheui/rpaheui-c
[8524] translation-task}
[translation:info] usession directory: /tmp/usession-default-9
[Timer] Timings:
[Timer] annotate                       ---   6.3 s
[Timer] rtype_lltype                   ---  26.1 s
[Timer] pyjitpl_lltype                 --- 236.3 s
[Timer] backendopt_lltype              ---  70.5 s
[Timer] stackcheckinsertion_lltype     ---   1.6 s
[Timer] database_c                     ---  78.5 s
[Timer] source_c                       ---  26.4 s
[Timer] compile_c                      ---  81.5 s
[Timer] ==========================================
[Timer] Total:                         --- 527.3 s
cp rpaheui-c /usr/local/bin/rpaheui
cp: 일반 파일 '/usr/local/bin/rpaheui'을(를) 생성할 수 없음: 허가 거부
Makefile:22: 'install' 타겟에 대한 명령이 실패했습니다
make: *** [install] 오류 1

이렇게 오류가 납니다

**Comment by Seojune** [comment]
apt install libffi6를 했더니 libffi6 is already the newest version(3.2.1-4)이라고 합니다

**Comment by minacle** [comment]
`make install` 로 설치하시려거든 `/usr/local/bin` 디렉토리에 쓰기 권한이 있어야 합니다.
`make` 하시면 현재 디렉토리에서 빌드하여 사용할 수 있습니다.

**Comment by Seojune** [comment]
아 덕분에 설치했습니다 감사합니다!
아직 갈길이 머네요

**Comment by youknowone** [comment]
해결됐다니 다행입니다. 권한 문제는 보통 시스템에 설치할때는 sudo 등으로 권한을 획득해 설치하곤 합니다.

@minacle 도와주셔서 감사합니다 :)
